### PR TITLE
allow control over large records on kinesis/firehose

### PR DESCRIPTION
**Pull request by andreineculau**
from https://github.com/tobiipro/aws-util-firecloud/pull/6#discussion_r239640743

### CODE REVIEW

**Comment by andreineculau** [comment]
no need for the cynicism. That's just how I interpreted your comment 
https://github.com/tobiipro/aws-util-firecloud/pull/6#discussion_r239640743 . And to the point, it sounds like you understand the logic of `onLargeRecordEntries` just fine 😉 

Back to your initial suggestion, having a helper function to check **a** record size (or record sizes of a multiple records means that you run `JSON.stringify` twice over possibly large records). An alternative would be a prep function that would return "recordBatches AND tooLargeRecords". The caller could then decide what to do with the tooLargeRecords, and maybe forward recordBatches to a  putRecordBatches function.

**Comment by IanSavchenko** [comment]
I wanted to (re)move out code, not add more code 😄 

Yes, I wanted to run serialization twice, but make logic more simple. I don't think that it will be a huge performance hit and it's not like we are fighting for performance here. Also, I expect 90% of the records to be small, so it won't be that critical either. 

From a performance perspective, it can be optimized in a way that:
1) we make it in a way that function accepts only strings (stringified records)
2) we can pre-check size in bytes only for those stringified records that have bigger length (like 500k)

**Comment by andreineculau** [comment]
there's performance and performance... stringifying 500 records of 1MB each = 6.5 **seconds** in a simple local test.

If we say we don't care about backward compat, we can do like you say in 2 steps. It has the added benefit that the `putRecords` functions become agnostic of serialization. The downside is that now you'll need two calls `ourFirehose.recordsToJSON + ourFirehose.putRecords` but you can't have the cake and eat it too.

Otherwise, a middle ground would be to at least return the records that were skipped. The app could decide what to do with them. (updated the PR with this, not saying that I favour it, just that it was easy to do it)

**Comment by andreineculau** [comment]
> Probably, the right solution would be to check the size of every record in the batch and fail early (or ignore them, depending on a flag) if some of them are oversized, even before attempting to send any record. In this way, we would provide some integrity of operation (maybe).

Hmm, that sounds so similar to... something... I know! my first iteration 😝 the only diff: change callback to flag

**Pull request merged**
